"""Snapshot SDL_net 3.2.0's unconditional C exports; C++ infers function signatures."""
import argparse
import pathlib
import re

root = pathlib.Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument("header",type=pathlib.Path)
parser.add_argument("--check",action="store_true")
args = parser.parse_args()
header = re.sub(r"/\*.*?\*/","",args.header.read_text(),flags=re.S)
for part,value in (("MAJOR",3),("MINOR",2),("MICRO",0)):
    assert re.search(rf"#define\s+SDL_NET_{part}_VERSION\s+{value}\b",header)
names = re.findall(r"extern SDL_DECLSPEC[^;]+?SDLCALL\s+(NET_\w+)\([^;]*\);",header)
assert len(names) == len(set(names)) == 34
banner = "// Generated by tools/generate_net_bindings.py; SDL_net 3.2.0.\n"
casts = "#pragma once\n"+banner
types = banner
register = banner
for name,body in re.findall(r"typedef enum (NET_\w+)\s*\{(.*?)\}\s*\w+;",header,re.S):
    casts += f"DAS_BIND_ENUM_CAST({name});\nDAS_BASE_BIND_ENUM_GEN({name},{name});\n"
    types += f'class Enum_{name} : public das::Enumeration {{ public: Enum_{name}() : das::Enumeration("{name}") {{\n'
    types += f'external=true; cppName="{name}"; baseType=(das::Type)das::ToBasicType<das::underlying_type<{name}>::type>::type;\n'
    for value in re.findall(r"\bNET_\w+",body):
        types += f'addIEx("{value[4:]}","{value}",int64_t({value}),das::LineInfo());\n'
    types += "} };\n"
    register += f"addEnumeration(new Enum_{name}());\n"
for name in ("NET_Address","NET_Server","NET_StreamSocket","NET_DatagramSocket"):
    types += f"MAKE_TYPE_FACTORY({name},{name});\n"
    register += f'addAnnotation(new DummyTypeAnnotation("{name}","{name}",1,1));\n'
name="NET_Datagram"
types += f'MAKE_TYPE_FACTORY({name},{name});\nnamespace das {{ struct {name}Annotation : ManagedStructureAnnotation<{name},false> {{\n'
types += f'{name}Annotation(ModuleLibrary& lib):ManagedStructureAnnotation("{name}",lib) {{\n'
for field in ["addr","port","buf","buflen"]:
    script_field = "address" if field == "addr" else field
    types += f'addField<DAS_BIND_MANAGED_FIELD({field})>("{script_field}","{field}");\n'
types += "} }; }\n"
register += f"addAnnotation(new {name}Annotation(lib));\n"
for name,value in re.findall(r'^#define\s+(NET_\w+)\s+([^\n]+)',header,re.M):
    if value.lstrip().startswith('"') or re.fullmatch(r'\s*0x[0-9A-Fa-f]+\s*',value):
        register += f'addConstant(*this,"{name}",{name});\n'
register += ''.join(f"BIND({name});\n" for name in names)
for filename,content in [('net_casts.inc',casts),('net_types.inc',types),('net_functions.inc',register)]:
    path=root/'src/libraries/generated'/filename
    if args.check:
        assert path.read_text()==content, f"Stale {filename}"
    else:
        path.parent.mkdir(parents=True,exist_ok=True)
        path.write_bytes(content.encode())
print(f"SDL_net: {len(names)} declarations")
