"""Snapshot the simple exported C declarations in the pinned SDL_image header.

Native signatures are inferred by DAS_BIND_FUN, not reimplemented by this tool.
This deliberately handles only SDL_image 3.2.4's unconditional function exports;
changing the version/header layout requires review. No generator is needed by consumers.
"""
import argparse
import pathlib
import re

root = pathlib.Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument("header", type=pathlib.Path)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
header = args.header.read_text()
for part, value in (("MAJOR",3),("MINOR",2),("MICRO",4)):
    assert re.search(rf"#define\s+SDL_IMAGE_{part}_VERSION\s+{value}\b",header), "Review SDL_image version"
names = re.findall(r"extern SDL_DECLSPEC[^;]+?SDLCALL\s+(IMG_\w+)\([^;]*\);", header)
assert len(names) == len(set(names)) == 59, "Review SDL_image declaration census"
output = "// Generated by tools/generate_image_bindings.py; SDL_image 3.2.4.\n"
output += "".join(f"BIND({name});\n" for name in names)
path = root / "src/libraries/generated/image_functions.inc"
if args.check:
    assert path.read_text() == output, "SDL_image snapshot is stale"
else:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(output.encode("utf-8"))
print(f"SDL_image: {len(names)} declarations")
