"""Snapshot SDL_sound 3.2.0's unconditional C exports; C++ infers function signatures."""
import argparse
import pathlib
import re

root = pathlib.Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument("header",type=pathlib.Path)
parser.add_argument("--check",action="store_true")
args = parser.parse_args()
header = re.sub(r"/\*.*?\*/","",args.header.read_text(),flags=re.S)
for part,value in (("MAJOR",3),("MINOR",2),("MICRO",0)):
    assert re.search(rf"#define\s+SDL_SOUND_{part}_VERSION\s+{value}\b",header)
names = re.findall(r"extern SDL_DECLSPEC[^;]+?SDLCALL\s+(Sound_\w+)\([^;]*\);",header)
assert len(names) == len(set(names)) == 17
banner = "// Generated by tools/generate_sound_bindings.py; SDL_sound 3.2.0.\n"
casts = "#pragma once\n"+banner
types = banner
register = banner
for name,body in re.findall(r"typedef enum (Sound_\w+)\s*\{(.*?)\}\s*\w+;",header,re.S):
    casts += f"DAS_BIND_ENUM_CAST({name});\nDAS_BASE_BIND_ENUM_GEN({name},{name});\n"
    types += f'class Enum_{name} : public das::Enumeration {{ public: Enum_{name}() : das::Enumeration("{name}") {{\n'
    types += f'external=true; cppName="{name}"; baseType=(das::Type)das::ToBasicType<das::underlying_type<{name}>::type>::type;\n'
    for value in re.findall(r"\bSOUND_SAMPLEFLAG_\w+",body):
        types += f'addIEx("{value}","{value}",int64_t({value}),das::LineInfo());\n'
    types += "} };\n"
    register += f"addEnumeration(new Enum_{name}());\n"
for name in ("Sound_Sample","Sound_DecoderInfo"):
    types += f"MAKE_TYPE_FACTORY({name},{name});\n"
    register += f'addAnnotation(new DummyTypeAnnotation("{name}","{name}",1,1));\n'
register += ''.join(f"BIND({name});\n" for name in names)
for filename,content in [('sound_casts.inc',casts),('sound_types.inc',types),('sound_functions.inc',register)]:
    path=root/'src/libraries/generated'/filename
    if args.check:
        assert path.read_text()==content, f"Stale {filename}"
    else:
        path.parent.mkdir(parents=True,exist_ok=True)
        path.write_bytes(content.encode())
print(f"SDL_sound: {len(names)} declarations")
