"""Generate nominal uint64 GPU handles at the script/native adapter boundary.

The checked registries remain internal uint64 maps. SDL's actual pointer API is
not changed. Only the explicitly listed checked-adapter signatures are rewritten.
"""
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]
KINDS = ('Buffer', 'IndexBuffer', 'Texture', 'Volume', 'Readback', 'Shader',
         'Sampler', 'Pipeline', 'CommandBuffer', 'RenderPass')
SPECS = {}

def add(name, result=None, **args):
    SPECS['SDL_' + name] = (result, args)

for name in ('CreateGPUDataBuffer', 'CreateGPUFloatVertexBuffer'):
    add(name, 'Buffer')
for name in ('ReleaseGPUDataBuffer', 'UpdateGPUDataBuffer', 'SetGPUDataBufferNameChecked'):
    add(name, id='Buffer')
add('CopyGPUDataBuffer', source='Buffer', destination='Buffer')
add('RequestGPUBufferReadback', 'Readback', id='Buffer')
add('CreateGPUCheckedIndexBuffer', 'IndexBuffer')
add('ReleaseGPUCheckedIndexBuffer', id='IndexBuffer')
for name in ('CreateGPUColorTargetTexture', 'CreateGPUTypedTransferTexture',
             'CreateGPUColorTransferTexture', 'CreateGPUTransferTexture'):
    add(name, 'Texture')
for name in ('GenerateGPUTextureMipmapsChecked', 'ReleaseGPUTransferTexture',
             'UploadGPUTextureRegion', 'SetGPUTransferTextureNameChecked'):
    add(name, id='Texture')
for name in ('BlitGPUTextureChecked', 'CopyGPUTextureRegion'):
    add(name, source='Texture', destination='Texture')
add('RequestGPUTextureReadback', 'Readback', id='Texture')
add('CreateGPUVolume', 'Volume')
for name in ('ReleaseGPUVolume', 'UploadGPUVolume'):
    add(name, id='Volume')
add('CopyGPUVolume', source='Volume', destination='Volume')
add('RequestGPUVolumeReadback', 'Readback', id='Volume')
for name in ('PollGPUReadback', 'WaitGPUReadback', 'ReadGPUReadback', 'ReleaseGPUReadback'):
    add(name, id='Readback')
for name in ('CreateGPUCheckedShader', 'LoadGPUCheckedShader'):
    add(name, 'Shader')
for name in ('ReleaseGPUCheckedShader', 'GetGPUCheckedShaderInfo', 'GetGPUCheckedShaderEntryPoint'):
    add(name, id='Shader')
add('GetGPUShaderEntryPointValue', shader='Shader')
add('CreateGPUCheckedSampler', 'Sampler')
for name in ('ReleaseGPUCheckedSampler', 'GetGPUCheckedSamplerInfo'):
    add(name, id='Sampler')
add('CreateGPUCheckedGraphicsPipeline', 'Pipeline', vertex='Shader', fragment='Shader')
for name in ('ReleaseGPUCheckedGraphicsPipeline', 'GetGPUCheckedGraphicsPipelineInfo'):
    add(name, id='Pipeline')
add('AcquireGPUCommandBufferChecked', 'CommandBuffer')
for name in ('CancelGPUCommandBufferChecked', 'SubmitGPUCommandBufferChecked',
             'GPURecordingDiscard', 'PushGPUUniformBytesChecked', 'PushGPUUniformVectorsChecked'):
    add(name, command='CommandBuffer')
add('BeginGPURenderPassChecked', 'RenderPass', command='CommandBuffer', target='Texture')
for name in ('EndGPURenderPassChecked', 'SetGPUViewportChecked', 'SetGPUScissorChecked',
             'SetGPUBlendConstantsChecked', 'DrawGPUPrimitivesChecked', 'DrawGPUIndexedPrimitivesChecked'):
    add(name, **{'pass': 'RenderPass'})
add('BindGPUGraphicsPipelineChecked', **{'pass': 'RenderPass', 'pipeline': 'Pipeline'})
add('BindGPUIndexBufferChecked', **{'pass': 'RenderPass', 'index': 'IndexBuffer'})
add('BindGPUVertexBuffersChecked', **{'pass': 'RenderPass', 'buffers': 'Buffer'})
add('BindGPUSamplersChecked', **{'pass': 'RenderPass', 'textures': 'Texture', 'samplers': 'Sampler'})

def handle(kind):
    return f'Gpu{kind}Handle'

def outputs():
    signatures = {}
    for path in sorted((ROOT / 'src').glob('sdl3*.h')):
        for match in re.finditer(r'inline\s+([^\n{}]+?)\s+(SDL_\w+)\(([^{};]+?)\)\s*\{', path.read_text()):
            rt, name, params = match.groups()
            if name in SPECS:
                signatures[name] = (rt.strip(), [' '.join(p.split()) for p in params.split(',')])
    assert signatures.keys() == SPECS.keys(), SPECS.keys() - signatures.keys()
    banner = '// Generated by tools/generate_gpu_handles.py. Do not edit.\n'
    types = [banner, '#pragma once\n#include "daScript/daScript.h"\n#include "daScript/ast/ast_handle.h"\n#include <cstdint>\n#include <type_traits>\n']
    registration = [banner]
    for kind in KINDS:
        name = handle(kind)
        types.append(f'''// Native registration of `typedef distinct {name} = uint64`.
struct {name} {{
    uint64_t value = 0;
    {name}() = default;
    explicit {name}(uint64_t v) : value(v) {{}}
    operator uint64_t() const {{ return value; }}
}};
static_assert(sizeof({name}) == sizeof(uint64_t));
static_assert(alignof({name}) == alignof(uint64_t));
static_assert(std::is_trivially_copyable_v<{name}>);
namespace das {{
template <> struct cast<{name}> {{
    static __forceinline {name} to(vec4f x) {{ return {name}(cast<uint64_t>::to(x)); }}
    static __forceinline vec4f from({name} x) {{ return cast<uint64_t>::from(x.value); }}
}};
template <> struct WrapType<{name}> {{ enum {{ value = true }}; typedef uint64_t type; typedef uint64_t rettype; }};
template <> struct WrapArgType<{name}> {{
    struct type : {name} {{ type(uint64_t v) : {name}(v) {{}} }};
}};
}}
MAKE_DISTINCT_TYPE_FACTORY({name},{name});
''')
        registration.append(f'addAnnotation(new DistinctTypeAnnotation("{name}", makeType<uint64_t>(lib), "{name}"));\n')
    wrappers = [banner, '#pragma once\n#include "gpu_handle_types.h"\n',
                '#include "sdl3_gpu_recording.h"\n#include "sdl3_gpu_volume.h"\n#include "sdl3_gpu_utilities.h"\n#include "sdl3_result_adapters.h"\n',
                'namespace sdl3_handles {\n']
    for name, (kind, args) in sorted(SPECS.items()):
        rt, params = signatures[name]
        typed, forwarded, found = [], [], set()
        for param in params:
            pname = re.search(r'(\w+)$', param)[1]
            if pname in args:
                found.add(pname)
                if 'TArray' in param:
                    # These two internal implementations read nominal array elements
                    # directly. No temporary ID arrays or aliasing casts are needed.
                    assert 'uint64_t' in param or re.search(r'TArray<\w+Handle>', param)
                    param = re.sub(r'TArray<[^>]+>', f'TArray<{handle(args[pname])}>', param)
                    forwarded.append(pname)
                else:
                    assert 'uint64_t' in param
                    param = param.replace('uint64_t', handle(args[pname]))
                    forwarded.append(f'uint64_t({pname})')
            else:
                assert 'uint64_t' not in param, (name, pname)
                forwarded.append(pname)
            typed.append(param)
        assert found == args.keys(), (name, found, args)
        call = f'::{name}({", ".join(forwarded)})'
        result = handle(kind) if kind else rt
        if kind:
            assert rt == 'uint64_t'
            call = f'{result}({call})'
        wrappers.append(f'inline {result} {name}({", ".join(typed)}) {{\n    return {call};\n}}\n')
    wrappers.append('}\n')
    return {'gpu_handle_types.h': ''.join(types), 'gpu_handle_registration.inc': ''.join(registration),
            'gpu_handle_adapters.h': ''.join(wrappers)}

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for filename, content in outputs().items():
        path = ROOT / 'src/generated' / filename
        if args.check:
            assert path.read_text(encoding='utf-8') == content, f'Stale {path}'
        else:
            path.write_text(content, encoding='utf-8', newline='\n')
    registration = (ROOT / 'src/module_sdl3.cpp').read_text(encoding='utf-8')
    for name in SPECS:
        assert registration.count(f'DAS_BIND_FUN(sdl3_handles::{name})') == 1, name
        assert f'DAS_BIND_FUN({name})' not in registration, f'Untyped overload: {name}'
        assert registration.count(f'"sdl3_handles::{name}"') == 1, f'AOT name: {name}'
    print(f'GPU handles: {len(KINDS)} nominal types, {len(SPECS)} adapter signatures')

if __name__ == '__main__':
    main()
