"""Snapshot SDL_shadercross commit 1ff05bec573988a98ef9e0260b4da44f512b8367's unconditional C exports; C++ infers function signatures."""
import argparse
import pathlib
import re

root = pathlib.Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument("header",type=pathlib.Path)
parser.add_argument("--check",action="store_true")
args = parser.parse_args()
header = re.sub(r"/\*.*?\*/","",args.header.read_text(),flags=re.S)
for part,value in (("MAJOR",3),("MINOR",0),("MICRO",0)):
    assert re.search(rf"#define\s+SDL_SHADERCROSS_{part}_VERSION\s+{value}\b",header)
names = re.findall(r"extern SDL_DECLSPEC[^;]+?SDLCALL\s+(SDL_ShaderCross_\w+)\([^;]*\);",header)
assert len(names) == len(set(names)) == 15
banner = "// Generated by tools/generate_shadercross_bindings.py; SDL_shadercross commit 1ff05bec573988a98ef9e0260b4da44f512b8367.\n"
casts = "#pragma once\n"+banner
types = banner
register = banner
for name,body in re.findall(r"typedef enum (SDL_ShaderCross_\w+)\s*\{(.*?)\}\s*\w+;",header,re.S):
    casts += f"DAS_BIND_ENUM_CAST({name});\nDAS_BASE_BIND_ENUM_GEN({name},{name});\n"
    types += f'class Enum_{name} : public das::Enumeration {{ public: Enum_{name}() : das::Enumeration("{name}") {{\n'
    types += f'external=true; cppName="{name}"; baseType=(das::Type)das::ToBasicType<das::underlying_type<{name}>::type>::type;\n'
    for value in re.findall(r"\bSDL_SHADERCROSS_\w+",body):
        script_value = value.removeprefix("SDL_SHADERCROSS_")
        types += f'addIEx("{script_value}","{value}",int64_t({value}),das::LineInfo());\n'
    types += "} };\n"
    register += f"addEnumeration(new Enum_{name}());\n"
# Declaration order preserves nested field dependencies.
structs=re.findall(r"typedef struct (SDL_ShaderCross_\w+)\s*\{(.*?)\}\s*\w+;",header,re.S)
assert len(structs)==7
for name,body in structs:
    types += f'MAKE_TYPE_FACTORY({name},{name});\nnamespace das {{ struct {name}Annotation : ManagedStructureAnnotation<{name},false> {{\n'
    types += f'{name}Annotation(ModuleLibrary& lib):ManagedStructureAnnotation("{name}",lib) {{\n'
    for field in re.findall(r"(\w+)\s*;",body):
        types += f'addField<DAS_BIND_MANAGED_FIELD({field})>("{field}");\n'
    types += "} }; }\n"
    register += f"addAnnotation(new {name}Annotation(lib));\n"
for name,value in re.findall(r'^#define\s+(SDL_SHADERCROSS_\w+)\s+([^\n]+)',header,re.M):
    if value.lstrip().startswith('"'):
        register += f'addConstant(*this,"{name}",{name});\n'
register += ''.join(f"BIND({name});\n" for name in names)
for filename,content in [('shadercross_casts.inc',casts),('shadercross_types.inc',types),('shadercross_functions.inc',register)]:
    path=root/'src/libraries/generated'/filename
    if args.check:
        assert path.read_text()==content, f"Stale {filename}"
    else:
        path.parent.mkdir(parents=True,exist_ok=True)
        path.write_bytes(content.encode())
print(f"SDL_shadercross: {len(names)} declarations, {len(structs)} structs")
