"""Snapshot SDL_ttf 3.2.2's unconditional C exports; C++ infers function signatures."""
import argparse
import pathlib
import re

root = pathlib.Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument("header",type=pathlib.Path)
parser.add_argument("--check",action="store_true")
args = parser.parse_args()
header = re.sub(r"/\*.*?\*/","",args.header.read_text(),flags=re.S)
for part,value in (("MAJOR",3),("MINOR",2),("MICRO",2)):
    assert re.search(rf"#define\s+SDL_TTF_{part}_VERSION\s+{value}\b",header)
names = re.findall(r"extern SDL_DECLSPEC[^;]+?SDLCALL\s+(TTF_\w+)\([^;]*\);",header)
assert len(names) == len(set(names)) == 117
banner = "// Generated by tools/generate_ttf_bindings.py; SDL_ttf 3.2.2.\n"
casts = "#pragma once\n"+banner
types = banner
register = banner
for name,body in re.findall(r"typedef enum (TTF_\w+)\s*\{(.*?)\}\s*\w+;",header,re.S):
    casts += f"DAS_BIND_ENUM_CAST({name});\nDAS_BASE_BIND_ENUM_GEN({name},{name});\n"
    types += f'class Enum_{name} : public das::Enumeration {{ public: Enum_{name}() : das::Enumeration("{name}") {{\n'
    types += f'external=true; cppName="{name}"; baseType=(das::Type)das::ToBasicType<das::underlying_type<{name}>::type>::type;\n'
    for value in re.findall(r"\bTTF_\w+",body):
        types += f'addIEx("{value[4:]}","{value}",int64_t({value}),das::LineInfo());\n'
    types += "} };\n"
    register += f"addEnumeration(new Enum_{name}());\n"
for name in ("TTF_Font","TTF_TextEngine","TTF_TextData"):
    types += f"MAKE_TYPE_FACTORY({name},{name});\n"
    register += f'addAnnotation(new DummyTypeAnnotation("{name}","{name}",1,1));\n'
for name,fields in {
    "TTF_Text": ["text","num_lines","refcount","internal"],
    "TTF_GPUAtlasDrawSequence": ["atlas_texture","xy","uv","num_vertices","indices","num_indices","image_type","next"],
    "TTF_SubString": ["flags","offset","length","line_index","cluster_index","rect"],
}.items():
    types += f'MAKE_TYPE_FACTORY({name},{name});\nnamespace das {{ struct {name}Annotation : ManagedStructureAnnotation<{name},false> {{\n'
    types += f'{name}Annotation(ModuleLibrary& lib):ManagedStructureAnnotation("{name}",lib) {{\n'
    for field in fields:
        types += f'addField<DAS_BIND_MANAGED_FIELD({field})>("{field}");\n'
    types += "} }; }\n"
    register += f"addAnnotation(new {name}Annotation(lib));\n"
for name,value in re.findall(r'^#define\s+(TTF_\w+)\s+([^\n]+)',header,re.M):
    if value.lstrip().startswith('"') or re.fullmatch(r'\s*0x[0-9A-Fa-f]+\s*',value):
        register += f'addConstant(*this,"{name}",{name});\n'
register += ''.join(f"BIND({name});\n" for name in names)
for filename,content in [('ttf_casts.inc',casts),('ttf_types.inc',types),('ttf_functions.inc',register)]:
    path=root/'src/libraries/generated'/filename
    if args.check:
        assert path.read_text()==content, f"Stale {filename}"
    else:
        path.parent.mkdir(parents=True,exist_ok=True)
        path.write_bytes(content.encode())
print(f"SDL_ttf: {len(names)} declarations")
