"""Generate daScript registrations from Clang's SDL3 AST (no Python packages).

The small allowlist is intentional. Ownership, event unions and callbacks require
manual policy; adapters live in src/sdl3_adapters.h and are never overwritten.
"""
import argparse
import json
import re
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]


def walk(node):
    yield node
    for child in node.get("inner", []):
        yield from walk(child)


def generate(clang, include):
    spec = json.loads((ROOT / "tools/bindings.json").read_text())
    command = [clang, "-x", "c", "-std=c11", "-fsyntax-only", "-Wno-pragma-pack",
               "-I", str(include), "-Xclang", "-ast-dump=json",
               str(include / "SDL3/SDL.h")]
    result = subprocess.run(command, capture_output=True, text=True, encoding="utf-8")
    if result.returncode:
        raise RuntimeError(result.stderr)
    nodes = list(walk(json.loads(result.stdout)))
    functions = {n["name"]: n for n in nodes
                 if n.get("kind") == "FunctionDecl" and n.get("name") in spec["functions"]}
    records = {n["name"]: n for n in nodes
               if n.get("kind") == "RecordDecl" and n.get("completeDefinition")
               and n.get("name") in spec["structs"]}
    missing = set(spec["functions"]) - functions.keys()
    if missing:
        raise RuntimeError(f"Missing SDL declarations: {sorted(missing)}")
    banner = "// Generated by tools/generate_bindings.py. Do not edit.\n"
    enums = {n["name"]: n for n in nodes if n.get("kind") == "EnumDecl"
             and n.get("name") in spec.get("enums", {}) and n.get("inner")}
    missing_enums = set(spec.get("enums", {})) - enums.keys()
    if missing_enums:
        raise RuntimeError(f"Missing enums: {sorted(missing_enums)}")
    enum_registrations = []
    types = [banner]
    for name, selected in spec.get("enums", {}).items():
        found = {}; value = -1
        for item in enums[name]["inner"]:
            if item.get("kind") != "EnumConstantDecl":
                continue
            explicit = [v["value"] for v in walk(item) if v.get("kind") == "ConstantExpr" and "value" in v]
            value = int(explicit[0]) if explicit else value + 1
            found[item["name"]] = value
        if set(selected) != set(found) or len(set(selected.values())) != len(selected):
            raise RuntimeError(f"Enum members differ from policy: {name}")
        types.append(f"DAS_BIND_ENUM_CAST({name});\nDAS_BASE_BIND_ENUM_GEN({name},{name});\n")
        types.append(f"static_assert(sizeof({name}) == 4);\nclass Enumeration_{name} : public das::Enumeration {{\n"
                     f"public: Enumeration_{name}() : das::Enumeration(\"{name}\") {{\n"
                     f"external=true; cppName=\"{name}\"; baseType=(das::Type)das::ToBasicType<das::underlying_type<{name}>::type>::type;\n")
        for member, alias in selected.items():
            value = found[member]
            if not -(2**31) <= value < 2**31:
                raise RuntimeError(f"Enum value outside supported int32 range: {name}.{member}")
            types.append(f"static_assert(int64_t({member}) == {value}LL);\naddIEx(\"{alias}\",\"{member}\",int64_t({member}),das::LineInfo());\n")
        types.append("} };\n")
        enum_registrations.append(f"addEnumeration(new Enumeration_{name}());\n")
    for name in spec["opaque_types"] + list(spec["structs"]):
        types.append(f"MAKE_TYPE_FACTORY({name}, {name});\n")
    types.append("namespace das {\n")
    for name, fields in spec["structs"].items():
        found = {n.get("name") for n in records[name].get("inner", []) if n.get("kind") == "FieldDecl"}
        if not set(fields) <= found:
            raise RuntimeError(f"Fields missing in {name}: {set(fields) - found}")
        types.append(f"struct {name}Annotation : ManagedStructureAnnotation<{name}, false> {{\n"
                     f"    {name}Annotation(ModuleLibrary & lib) : ManagedStructureAnnotation(\"{name}\", lib) {{\n")
        for field in fields:
            das_name = spec.get("field_names", {}).get(f"{name}.{field}", field)
            types.append(f'        addField<DAS_BIND_MANAGED_FIELD({field})>("{das_name}", "{field}");\n')
        types.append("    }\n};\n")
    types.append("} // namespace das\n")
    registrations = [banner] + enum_registrations
    for name in spec["opaque_types"]:
        registrations.append(f'addAnnotation(new DummyTypeAnnotation("{name}", "{name}", 1, 1));\n')
    # addField resolves nested record annotations immediately. Policy order is
    # not a declaration order (pipeline state may precede depth/stencil state).
    ordered_records, completed, visiting = [], set(), set()
    def register_after_dependencies(name):
        if name in completed:
            return
        if name in visiting:
            raise RuntimeError(f"Cyclic selected record annotation dependency: {name}")
        visiting.add(name)
        dependencies = set()
        for field in records[name].get("inner", []):
            if field.get("kind") == "FieldDecl" and field.get("name") in spec["structs"][name]:
                field_type = field["type"].get("desugaredQualType", field["type"]["qualType"])
                dependencies.update(re.findall(r"\b[A-Za-z_]\w*\b", field_type))
        for dependency in spec["structs"]:
            if dependency in dependencies:
                register_after_dependencies(dependency)
        visiting.remove(name)
        completed.add(name)
        ordered_records.append(name)
    for name in spec["structs"]:
        register_after_dependencies(name)
    for name in ordered_records:
        registrations.append(f"addAnnotation(new {name}Annotation(lib));\n")
    for name, ctype in spec["constants"].items():
        registrations.append(f'addConstant(*this, "{name}", static_cast<{ctype}>({name}));\n')
    manifest = {}
    for name in spec["functions"]:
        decl = functions[name]
        if decl.get("variadic"):
            raise RuntimeError(f"Variadic function requires an adapter: {name}")
        args = [n for n in decl.get("inner", []) if n.get("kind") == "ParmVarDecl"]
        argnames = [n.get("name", f"arg{i}") for i, n in enumerate(args)]
        signature = decl["type"]["qualType"]
        manifest[name] = {"signature": signature, "arguments": argnames}
        cpp_name = name + "Address" if name in ('SDL_SetClipboardData', 'SDL_SetWindowHitTest', 'SDL_SetEventFilter', 'SDL_GetEventFilter', 'SDL_AddEventWatch', 'SDL_RemoveEventWatch', 'SDL_FilterEvents', 'SDL_EnumerateDirectory', 'SDL_EnumerateStorageDirectory', 'SDL_SetAudioStreamGetCallback', 'SDL_SetAudioStreamPutCallback', 'SDL_OpenAudioDeviceStream', 'SDL_SetAudioPostmixCallback') else name
        if name in ('SDL_hid_open', 'SDL_hid_get_manufacturer_string', 'SDL_hid_get_product_string', 'SDL_hid_get_serial_number_string', 'SDL_hid_get_indexed_string'): cpp_name = name + "Wide"
        node = ", SimNode_ExtFuncCallAndCopyOrMove" if signature.split("(", 1)[0].strip() in spec["structs"] else ""
        registrations.append(f'// {signature}\naddExtern<DAS_BIND_FUN({name}){node}>(*this, lib, "{name}", '
                             f'SideEffects::worstDefault, "{cpp_name}")')
        if argnames:
            registrations.append("->args({" + ", ".join(json.dumps(a) for a in argnames) + "})")
        registrations.append(";\n")
    return {"sdl3_types.inc": "".join(types), "sdl3_functions.inc": "".join(registrations),
            "api.json": json.dumps(manifest, indent=2) + "\n"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--clang", default="clang")
    parser.add_argument("--sdl-include", required=True, type=Path)
    parser.add_argument("--check", action="store_true", help="Fail if committed output differs")
    args = parser.parse_args()
    output = ROOT / "src/generated"
    files = generate(args.clang, args.sdl_include.resolve())
    if args.check:
        stale = [name for name, text in files.items()
                 if not (output / name).exists() or (output / name).read_text(encoding="utf-8") != text]
        if stale:
            raise RuntimeError(f"Stale bindings: {stale}")
        print("Bindings are reproducible and up to date.")
    else:
        output.mkdir(parents=True, exist_ok=True)
        for name, text in files.items():
            (output / name).write_text(text, encoding="utf-8", newline="\n")
        print(f"Generated {len(files)} files in {output}")


if __name__ == "__main__":
    try:
        main()
    except (RuntimeError, OSError, KeyError) as error:
        print(error, file=sys.stderr)
        sys.exit(1)
