"""Generate daScript registrations from Clang's SDL3 AST (no Python packages).

The small allowlist is intentional. Ownership, event unions and callbacks require
manual policy; adapters live in src/sdl3_adapters.h and are never overwritten.
"""
import argparse
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]


def walk(node):
    yield node
    for child in node.get("inner", []):
        yield from walk(child)


def generate(clang, include):
    spec = json.loads((ROOT / "tools/bindings.json").read_text())
    command = [clang, "-x", "c", "-std=c11", "-fsyntax-only", "-Wno-pragma-pack",
               "-I", str(include), "-Xclang", "-ast-dump=json",
               str(include / "SDL3/SDL.h")]
    result = subprocess.run(command, capture_output=True, text=True, encoding="utf-8")
    if result.returncode:
        raise RuntimeError(result.stderr)
    nodes = list(walk(json.loads(result.stdout)))
    functions = {n["name"]: n for n in nodes
                 if n.get("kind") == "FunctionDecl" and n.get("name") in spec["functions"]}
    records = {n["name"]: n for n in nodes
               if n.get("kind") == "RecordDecl" and n.get("completeDefinition")
               and n.get("name") in spec["structs"]}
    missing = set(spec["functions"]) - functions.keys()
    if missing:
        raise RuntimeError(f"Missing SDL declarations: {sorted(missing)}")
    banner = "// Generated by tools/generate_bindings.py. Do not edit.\n"
    types = [banner]
    for name in spec["opaque_types"] + list(spec["structs"]):
        types.append(f"MAKE_TYPE_FACTORY({name}, {name});\n")
    types.append("namespace das {\n")
    for name, fields in spec["structs"].items():
        found = {n.get("name") for n in records[name].get("inner", []) if n.get("kind") == "FieldDecl"}
        if not set(fields) <= found:
            raise RuntimeError(f"Fields missing in {name}: {set(fields) - found}")
        types.append(f"struct {name}Annotation : ManagedStructureAnnotation<{name}, false> {{\n"
                     f"    {name}Annotation(ModuleLibrary & lib) : ManagedStructureAnnotation(\"{name}\", lib) {{\n")
        for field in fields:
            das_name = spec.get("field_names", {}).get(f"{name}.{field}", field)
            types.append(f'        addField<DAS_BIND_MANAGED_FIELD({field})>("{das_name}", "{field}");\n')
        types.append("    }\n};\n")
    types.append("} // namespace das\n")
    registrations = [banner]
    for name in spec["opaque_types"]:
        registrations.append(f'addAnnotation(new DummyTypeAnnotation("{name}", "{name}", 1, 1));\n')
    for name in spec["structs"]:
        registrations.append(f"addAnnotation(new {name}Annotation(lib));\n")
    for name, ctype in spec["constants"].items():
        registrations.append(f'addConstant(*this, "{name}", static_cast<{ctype}>({name}));\n')
    manifest = {}
    for name in spec["functions"]:
        decl = functions[name]
        if decl.get("variadic"):
            raise RuntimeError(f"Variadic function requires an adapter: {name}")
        args = [n for n in decl.get("inner", []) if n.get("kind") == "ParmVarDecl"]
        argnames = [n.get("name", f"arg{i}") for i, n in enumerate(args)]
        signature = decl["type"]["qualType"]
        manifest[name] = {"signature": signature, "arguments": argnames}
        registrations.append(f'// {signature}\naddExtern<DAS_BIND_FUN({name})>(*this, lib, "{name}", '
                             f'SideEffects::worstDefault, "{name}")')
        if argnames:
            registrations.append("->args({" + ", ".join(json.dumps(a) for a in argnames) + "})")
        registrations.append(";\n")
    return {"sdl3_types.inc": "".join(types), "sdl3_functions.inc": "".join(registrations),
            "api.json": json.dumps(manifest, indent=2) + "\n"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--clang", default="clang")
    parser.add_argument("--sdl-include", required=True, type=Path)
    parser.add_argument("--check", action="store_true", help="Fail if committed output differs")
    args = parser.parse_args()
    output = ROOT / "src/generated"
    files = generate(args.clang, args.sdl_include.resolve())
    if args.check:
        stale = [name for name, text in files.items()
                 if not (output / name).exists() or (output / name).read_text(encoding="utf-8") != text]
        if stale:
            raise RuntimeError(f"Stale bindings: {stale}")
        print("Bindings are reproducible and up to date.")
    else:
        output.mkdir(parents=True, exist_ok=True)
        for name, text in files.items():
            (output / name).write_text(text, encoding="utf-8", newline="\n")
        print(f"Generated {len(files)} files in {output}")


if __name__ == "__main__":
    try:
        main()
    except (RuntimeError, OSError, KeyError) as error:
        print(error, file=sys.stderr)
        sys.exit(1)
